# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='object ID')),
                ('app_name', models.CharField(max_length=30, verbose_name='application name')),
                ('model_name', models.CharField(max_length=30, verbose_name='model name')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'created'), (2, 'updated'), (3, 'deleted')], verbose_name='action')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date and time when the changes were made')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who made the action')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Ext Log',
                'verbose_name_plural': 'Ext Log',
            },
        ),
    ]
