# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('app', '0001_initial'),
        ('modeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('GenericDataGridView', 'Generic Data Grid'), ('GenericJobCard', 'JobCard'), ('GenericInvoice', 'Invoice')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(blank=True, default='', max_length=50)),
                ('date_range', models.BooleanField(default=False)),
                ('check_box', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App')),
                ('base_templates', models.ManyToManyField(related_name='base_templates', to='authentication.BaseTemplate')),
                ('list_display', models.ManyToManyField(to='modeller.ModelField')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modeller.ModelObject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
