# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='page.Page'),
        ),
        migrations.AddField(
            model_name='subtab',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtabs', to='page.Page'),
        ),
        migrations.AddField(
            model_name='subtab',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Tab'),
        ),
        migrations.AddField(
            model_name='basetemplate',
            name='groups',
            field=models.ManyToManyField(help_text='Select one or more groups that can access this Authentication level', to='auth.Group'),
        ),
    ]
